### ISSUE TITLE
Engine v2 timer manager design

### ISSUE THREAD

**Issue by liguangbo** [bitleak/lmstfy#117]
# Lmstfy v2 engine timer manager design

- Author: [Bob Li](https://github.com/liguangbo)

## Table of Contents

* [Introduction](#introduction)
* [Motivation or Background](#motivation-or-background)
* [Detailed Design](#detailed-design)
* [Test Design](#test-design)

## Introduction

A manager of timer. Manage a goroutine pool to pump specific queue, register self to redis and use lua script to check all timer manager alive.

## Motivation or Background

According to v2 design, we will allocate a timer_set to every queue. So there are thousands of timer_set need to pump, every time_set must be pumped every second. For pumping these timer_sets we can't repeat a single pumper, we need design a timer manager to manage pumper goroutine.

Lmstfy is a distributed system, every instance is same. In Lmstfy V1 we have only one timer_set need to be pumped, so every Lmstfy instance can pump every second that won't cause problem. But now, thousands of timer_sets need to be pumped, if we deploy 10+ Lmstfy instance, there will be tens of thousands of lua scripts needed to run in redis within one second. Haha, this is the disaster. So timer manager could reduce duplicate pump of the timer_set.

## Detailed Design

TimerManger structure
`sequence` int, this timer sequence number. for pick queue to pump
`pool` pool of pumper goroutine, plan to use https://github.com/Jeffail/tunny/tree/1b37d6cb867a93f37f313022f6b7cb5bfe6cdc1b
`name` this timer manager name, generated by ip+uuid
`queues` the queueManager(metaManager), get queues to pump

TimerManger's public API:
`Add` add jobid to timer_set
`Remove` remove job_id from time_set
`Name` return timer manager name
`Size` calculate timer_set size
`Shutdown` stop pump pool and sequence calculation

TimerManger's principle:

1. timer manager register

```
    ┌───────────────────┐    
    │                   │    
    │   TimerManager    │    
    │                   │    
    └───────────────────┘    
              │              
              │              
   HSET key name now()+ttl   
     repeat every second     
              │              
              │              
              ▼              
    ┌───────────────────┐    
    │                   │    
    │       Redis       │    
    │                   │    
    └───────────────────┘    
```

2.  timer sequence number calculation

```
     ┌───────────────────┐      
     │                   │      
     │   TimerManager    │      
     │                   │      
     └───────────────────┘      
               │                
               │                
               │                
┌──────────────┴───────────────┐
│run lua script(Pseudo code):  │
│servers = {}                  │
│for k,v in HGETALL key {      │
│    if v < now() {            │
│        HDEL key k            │
│    } else {                  │
│        server.insert(k)      │
│    }                         │
│}                             │
│return table.sort(servers)    │
└──────────────┬───────────────┘
               │                
               ▼                
     ┌───────────────────┐      
     │                   │      
     │       Redis       │      
     │                   │      
     └───────────────────┘      
```
The sequence number which timerManager in result servers is the temporary sequence number.
Sequence number 0 means pump all queue, the others timerManager pump queues divide equally.

3.  use sequence number filter queues each second, then distribute queue to pumper pool wait for goroutine.

## Test Design

- Add and Remove should be discovered
- sequence should calculated properly
- pump should execute timely

**Comment by git-hulk** [comment]
Great, overall looks good to me, except for the heartbeat part which checks every second may too sensible. I think we should use a longer heartbeat timeout and interval, e.g. timeout = 6s and interval = 6s/3, also can prevent the `master` was unsteady between servers.
