### ISSUE TITLE
DesignQuestion: 删除Job的策略

### ISSUE THREAD

**Issue by wymli** [bitleak/lmstfy#134]
想问下删除Job（Delete API）时的策略问题，在删除Job时只是删除了pool中的job，并没有删除timer zset中的对应Job句柄，请问这个的考虑是什么呢？
refer to https://github.com/bitleak/lmstfy/issues/26 ，看实践上是等待再次消费的时候自动删除掉   

但看代码: https://github.com/bitleak/lmstfy/blob/master/engine/redis/queue.go#L224-L225 ，PollQueues()在拉取ready队列的时候，似乎不管怎样都会让retry 减一并再度放到timer zset中，等待被调度到死信队列或ready队列。  
这中间并没有处理job已经被删除的情况。

按我的理解，对于一个已被ACK/Delete的job被再次调度到ready队列时，job被消费时（但因为job被删除，已不在pool中，会[再消费其他job](https://github.com/bitleak/lmstfy/blob/master/engine/redis/engine.go#L161-L162)）会一直不断递减retry，并加入timer zset，随后timer zset中的job会被调度到ready队列被消费，不断重复，直到retry=0，被timer zset调度到死信队列。  

不知道是不是我遗漏了关键代码，感谢解答~

**Comment by liguangbo** [comment]
> 想问下删除Job（Delete API）时的策略问题，在删除Job时只是删除了pool中的job，并没有删除timer zset中的对应Job句柄，请问这个的考虑是什么呢？

这是一个设计上不好的地方，因为 timer zset 中的 "job句柄" 包含了 jobID 和重试次数，导致如果想要删除这个 "句柄" 需要扫这个 timerset 可能会造成一些性能问题。在 v2（但是搞到一半还没时间继续） 的设计中会将重试次数从 "句柄" 中移除，放到 meta 里面，这样就可以进行清理了。

> 但看代码: https://github.com/bitleak/lmstfy/blob/master/engine/redis/queue.go#L224-L225 ，PollQueues()在拉取ready队列的时候，似乎不管怎样都会让retry 减一并再度放到timer zset中，等待被调度到死信队列或ready队列。
这中间并没有处理job已经被删除的情况。

只有极端情况才会这样，实际在 timer_set [pump](https://github.com/bitleak/lmstfy/blob/master/engine/redis/timer.go#L27) 到 read_queue 的时候会检查任务在 pool 内的状态。deleted 的任务会导致这个任务在 pump 到 ready 队列的时候从 timer_set 被删除，最多只重新进入 timer 一次。
极端情况，一个在就绪队列的任务，还没被消费，比如在堆积的时候被删除了，会导致 "句柄" 重新进入 timer_set 并在下一次 pump 被删除。

**Comment by wymli** [comment]
了解，感谢~
