### ISSUE TITLE
Retrospect monitor metrics and need to involve secondary storage

### ISSUE THREAD

**Issue by git-hulk** [bitleak/lmstfy#163]
Currently, we created the v2 engine based on v1 which only involves Redis metrics,
and we need to involve the secondary storage metrics as well in v2.

**Comment by Napoleon0621** [comment]
Hi Hulk @git-hulk ,
For now, I can come up with these metrics to be added:
1. storageAddJobs count
2. storageDelJobs count
3. storageSizes(with label: "namespace" and "queue")
Any opinion on this?

**Comment by git-hulk** [comment]
Sounds good

**Comment by Napoleon0621** [comment]
Considering the storageSizes metric involves a scan of the entire table, which may increase storage pressure, therefore we'll just ignore this metric for now.  There're certainly other ways to get this kind of size information.
