### ISSUE TITLE
Benchmark the secondary storage pumper

### ISSUE THREAD

**Issue by git-hulk** [bitleak/lmstfy#165]
### Search before asking

- [X] I had searched in the [issues](/https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Motivation

As a user, I want to know the performance of each part in system internal.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by Napoleon0621** [comment]
@git-hulk Hi Hulk,
Since our unit tests uses a spanner emulator instead of a real spanner instance as secondary storage, I'm not sure if it makes   sense to do storage pumper benchmarking storage pumper in unit tests.

**Comment by git-hulk** [comment]
@Napoleon0621 Will close this issue first, we can do it after we supports MySQL/PG.
