### ISSUE TITLE
Stop pumping from the secondary storage according to Redis volume

### ISSUE THREAD

**Issue by git-hulk** [bitleak/lmstfy#166]
### Search before asking

- [X] I had searched in the [issues](/https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Motivation

We regard the Redis as the cache tier when using the secondary storage,
so we need to take care of the cache since the storage volume may far bigger
than the cache.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by Napoleon0621** [comment]
@git-hulk Hi Hulk,
I'm thinking of using "mem_fragmentation_ratio" (used_memory_rss / used_memory) as the metric to decide whether stop pumping data from storage to redis.
Any thoughts on the threshold value? Will mem_fragmentation_ratio < 1.1 be an appropriate one?

**Comment by git-hulk** [comment]
Should use `used_memory`/`max_memory`, `mem_fragmentation_ratio` is used to measure the efficiency of memory allocator.

**Comment by Napoleon0621** [comment]
Okay, cool.
