### ISSUE TITLE
能否举例解释下Imstfy所支持的典型任务，举出若干Imstfy的典型使用场景？

### ISSUE THREAD

**Issue by weizmann** [bitleak/lmstfy#170]
### Search before asking

- [X] I had searched in the [issues](/https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Motivation

您好，我阅读了Imstfy在网上的两篇介绍文章和Golang api文档，但是对这个系统解决的问题场景（业务场景）没有很好地理解。
总结有以下若干问题，想在这里请教下（原谅我并没有开始仔细阅读源码）：

首先，怎么定义”任务“？我看到在api文档中的publish，定义了data []byte，似乎这个应该是任务的意思。但是在example中，data传入了"hello"。这个让我有点困惑。

我理解的任务，比如大数据平台的任务(java cmd)、cronjob任务(shell cmd)或GPU任务(更多的参数配置等)，需要有进程入口(shell/python/binary entry)以及参数，但是在Imstfy的文档中，暂时没有看到这些。所以想请教下，Imstfy所支持的“典型的任务场景”是哪些？是否方便举例一二？

如何理解Imstfy的“生产者”和“消费者”？如果将Imstfy看成一个黑盒的话，消费者会需要轮询Imstfy系统看任务运行(注意，是execute)的状态，还是会看任务是否到期可运行？

其次，我之所以找到Imstfy，是因为我司业务场景是需要有一个工序流场景。即，当用户提交了一个订单之后，有很多不同的CPU/GPU任务需要被调度，但是大多任务的运行时长可能会很长（由于这些任务内部足够单纯，可以不需要感知被调度的父节点等任务依赖信息，他们仅需要在失败或者成功的时候，设置任务状态即可）。目前调度器是采用定期(根据任务的不同，轮询间隔可能有10s/30s/60s不等)轮询任务状态的方式进行。现在，考虑到使用一些延迟队列来简化逻辑

不知道Imstfy所解决的业务场景中，是否对串行任务(即 job-A -> job-B -> job-C 这种)或者有DAG依赖关系的任务链，有方便的支持？

第三，作为选型的横向比对，能否帮忙对比下，在Imstfy的典型业务场景中，使用Imstfy和RabbitMQ的延迟队列的差异点？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
> 首先，怎么定义”任务“？我看到在api文档中的publish，定义了data []byte，似乎这个应该是任务的意思。但是在example中，data传入了"hello"。这个让我有点困惑。

这个就是任务的内容，用户传入什么在消费的时候就原样返回

> 不知道Imstfy所解决的业务场景中，是否对串行任务(即 job-A -> job-B -> job-C 这种)或者有DAG依赖关系的任务链，有方便的支持？

不在支持范围内
