### ISSUE TITLE
Add an API to list all queues?

### ISSUE THREAD

**Issue by TTWShell** [bitleak/lmstfy#203]
### Search before asking

- [X] I had searched in the [issues](/https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Motivation

We need to publish and consume jobs from the queues dynamically in our business model, but they cannot share the consumed worker between queues. So it requires us to create/delete the workers accordingly.

我们的业务场景需要动态的publish/ job到动态创建的queue中（业务决定，没办法共用queue），这要求我们根据业务场景动态的创建/删除对应的worker。

### Solution
Add a new API to list the existing queues and also send events if the queue is deleted or created.

增加一个queue列表API，则可以监听新创建的queue，根据这个列表，动态创建/回收worker。

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@TTWShell 现在的 Queue 是完全动态的，也就没办法感知存储里面有哪些队列。另外一种方式是支持静态 Queue，使用之前需要先通过 API 注册。
