### ISSUE TITLE
Can't start Lmstfy server by docker-compose

### ISSUE THREAD

**Issue by 1Ckpwee** [bitleak/lmstfy#211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/bitleak/lmstfy/issues) and found no similar issues.

### Version

master

### Minimal reproduce step

Steps:
1. `git clone https://github.com/bitleak/lmstfy.git`
2. `cd lmstfy`
3. `cd docker && docker-compose -p test-lmstfy up -d`

### What did you expect to see?

redis & Lmstfy server can be started

### What did you see instead?

Lmstfy server can not be started cause by panic while checking redis conf
```
goroutine 1 [running]:
2023-03-24 09:31:25 main.main()
2023-03-24 09:31:25     /lmstfy/server/main.go:195 +0x59d
2023-03-24 09:32:45 panic: Failed to post validate the config file: validate pool[default] err: redis appendonly MUST be 'yes' to prevent data loss
```

### Anything Else?

refer to PR #141 
it makes change as below:
```
        infoStr, err := cli.Info(ctx).Result()
        ...
	lines := strings.Split(infoStr, "\r\n")
	for _, line := range lines {
		fields := strings.Split(line, ":")
		if len(fields) != 2 {
			continue
		}
		switch fields[0] {
                ...
		case "aof_enabled":
			isAppendOnlyEnabled = fields[1] == "1"
		...
	}
	if !isAppendOnlyEnabled {
		return errors.New("redis appendonly MUST be 'yes' to prevent data loss")
	}
        ...
```
And we can see redis default config:
```
127.0.0.1:6379> info
# Server
redis_version:4.0.14
...
aof_enabled:0
...
```
`aof_enabled` default value is 0

### How to Do
run docker-compose with custom redis config

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @1Ckpwee, thanks for your feedback. 

It's an expected behavior, we need to check if the Redis AOF was enabled to prevent the data loss. And the latest version of the docker-compose file has fixed this issue, would you like to have a try? https://github.com/bitleak/lmstfy/blob/master/scripts/redis/docker-compose.yml#L13

**Comment by 1Ckpwee** [comment]
Currently not synced to [docker/docker-compose.yml](https://github.com/bitleak/lmstfy/blob/master/docker/docker-compose.yml) 
![image](https://user-images.githubusercontent.com/51103782/227425383-67ee06bb-9566-4746-b8df-37e71314134c.png)

**Comment by git-hulk** [comment]
@git-hulk Yes, good catch. Would you like to fix that?

**Comment by 1Ckpwee** [comment]
@git-hulk  Glad to try while free
