### ISSUE TITLE
Proposal: timer队列ZSET列表member去除重试次数tries

### ISSUE THREAD

**Issue by liguangbo** [bitleak/lmstfy#30]
## Introduction

lmstfy中的延时任务主要会经历三种数据结构的存储

1.  用来解决定时的timer队列，使用Zset实现。该zset内每个member可以解析出队列、jobID、剩余重试次数。member的score为任务的定时时间。在固定间隔内，系统会将当前系统时间之前的任务从timer队列转移到就绪队列，将重试次数用尽而还没有ack的任务转移到死信队列中。
1.  就绪队列，使用List实现。进入到就绪队列的任务将会被consume请求获取到进行操作。
1.  死信队列，使用List实现。保存过期还没有被ack等无法处理的任务用于回溯

近期有几个需求：

1.  完善consume与ack语义，既只能ack被consumed的任务。现有的ack语义实际上是delete语义，仅删除了任务内容，任务元信息并没有处理，依靠系统获取不到任务内容来慢慢消化被提前删掉的任务。
1.  fastack，既在消费了一次任务并且失败后，希望能立刻重试这个任务。需要提前将任务从timer队列移入就绪队列

以上几个需求都需要对timer队列进行操作，由于timer队列中的member包含重试次数tries，而ack等逻辑无法获取到tries等信息。因此目前timer队列的设计无法满足要求。

## Problem

在timer队列中操作任务的操作被称为pump。pump会根据tries的值决定这个任务移入死信队列还是就绪队列。因此获取tries的值是必须的。

原本的设计中，将tries存储在timer队列中的成员名称中。zset中每个member的构成：

```
{namespace len}{namespace}{queue len}{queue}{tries}{jobID len}{jobID}
```

这样可以节省额外获取tries的复杂操作，但是带来了无法操作timer中任务的问题。因为操作timer中的任务需要知道zset的member，这个member由tries组成，很多时候无法获得，逻辑上也不合理。可能需要改造。

## Design

目前timer队列的结构为：

```
ZADD test_queue member timestamp
member = {namespace len}{namespace}{queue len}{queue}{tries}{jobID len}{jobID}
timestamp = now+delaySecond或者ttr
```

所以pump部分获取任务的命令为：

```
local expiredMembers = redis.call("ZRANGEBYSCORE", zset_key, 0, now, "LIMIT", 0, limit)
```

需要将tries从member的构成中移除，本方案将tries从member中移入score中，变为score的小数部分。这样变更不会影响到旧任务的消费，还能够在指定时间内被pump。
未来timer队列的结构为：

```
ZADD test_queue member timestamp
member = {namespace len}{namespace}{queue len}{queue}{jobID len}{jobID}
timestamp = {now+delaySecond或者ttr}.{printf(%05d,tries)} 
```

pump部分获取任务的命令变更为：

```
local expiredMembersAndScores = redis.call("ZRANGEBYSCORE", zset_key, 0, (now+1, "WITHSCORES", "LIMIT", 0, limit)
```

还需要兼容旧版本的member，可以根据member的构成来判断是否包含tries，如果不包含tries则从score中获取重试次数。重试次数固定为小数点后5位（原本的重试上限为65535），防止精度问题，截取后六位进行roundup(ceil)。

使用这个方案能够平滑的过渡，旧数据能够被按时消费，新数据以新的方式存储，并能支持部分新的需求，比如fastack等。

**Comment by git-hulk** [comment]
ACK(DELETE) 后续也可以顺便尝试把 timer 里面的 JOB 删除
