### ISSUE TITLE
消息数据数据量过多，是否支持部分数据在磁盘，部分数据在内存？

### ISSUE THREAD

**Issue by lzjqcc** [bitleak/lmstfy#4]

**Comment by git-hulk** [comment]
@lzjqcc 这部分计划在做，其中一种方案是基于我们的磁盘 KV 存储 https://github.com/meitu/kvrocks 来做

**Comment by shiqwang** [comment]
这个kvrocks可以的话，用pika是不是也可以呢？

**Comment by git-hulk** [comment]
@shiqwang kvrocks 需要一些特殊原子支持，目前没法直接兼容，pika 也是一样。目前在基于 kvrocks 和 TiKV 的方案做设计。

**Comment by git-hulk** [comment]
https://github.com/KvrocksLabs/kvrocks

Kvrocks 已经支持 Lua, 直接把 Kvrocks 作为 LMSTFY 的 engine 即可，关闭 issue.
