### ISSUE TITLE
消费端处理非原子带来的问题

### ISSUE THREAD

**Issue by chensunny** [bitleak/lmstfy#41]
**Describe the bug**

整体的设计是通过 retry 的方式保证 数据可靠性，
其过程是通过 consumer sdk 在消费的时候，pop+ timer 的方式。

但是这个操作并非通过 lua 做原子的操作，可能在 pop 过程中进程 panic 导致这个 消息丢失没办法被其他进程消费 or 进入死信队列。

所以 PollQueues 这个函数的 BRPop 和 timer.Add 做成 lua 原子的可能会好点。虽然是小概率事件，但是这个场景丢的数据不太好排查和恢复

**Comment by liguangbo** [comment]
lua内只能执行非阻塞的命令，所以只能支持非阻塞的pop+timer。brpop在lua内被禁止执行。如果只做非阻塞部分似乎会让代码割裂，而且主要场景可能是阻塞场景用的比较多。

**Comment by ruoshan** [comment]
darn! you're spot on. My solution to this would be using BRPOPLPUSH to a tmp buf, and execute the `buf .pop; timer.add` in the lua script. @liguangbo what do you think?
