### ISSUE TITLE
Proposal: 优先级队列

### ISSUE THREAD

**Issue by liguangbo** [bitleak/lmstfy#47]
## Introduction

业务希望能够定义任务的优先级，在消费任务的时候可以优先消费任务权重高的任务。
同时，应该保证延迟时间优先，权重其次

## Problem

当前lmstfy数据一共分为四部分：
1.  timer_zset：一个zset，用来处理延时，元素为 {namespace len}{namespace}{queue len}{queue}{tries}{jobID len}{jobID}
1.  ready_queue：一个list，延时到期的任务会被放到这个队列等待消费，元素为 {tries}{jobID len}{jobID}
1.  data_pool：普通kv用来存放任务body，{namespace}{queue}{jobID}
1.  deadletter：一个list，重试次数为0的任务会进入这个队列等待销毁或者重新执行

实现优先级队列需要将ready_queue根据权重排序

#30 表述了希望能将timer_set ready_queue中元素的 tries去掉，在ack的时候可以检测这个任务是否被消费，也可以直接从zset中移除这个任务

## Design

为解决以上问题，方案如下：

1.  修改ready_queue为zset，因此timer_set的lua脚本中需要修改list命令为zset命令，消费函数中需要使用zpopmax以及bzpopmax，此命令需要redis>=5.0
1.  移除timer_set和ready_queue以及deadletter中元素的tries，将tries以及priority以及任务body存放在一起
1.  data_pool由简单kv替换成set，通过hgetall获取tries和priority

由于使用的特性需要redis5.0以上，切数据结构以及数据内容都有break change，计划实现一个新的engine，通过配置可以指定某个pool使用这个engine。通能过区分key也可以和和以前的pool使用同一个实例，并且通过配置migrateTo可以实现数据的迁移。

### timer lua

```
local zset_key = KEYS[1]
local output_queue_prefix = KEYS[2]
local pool_prefix = KEYS[3]
local output_deadletter_prefix = KEYS[4]
local now = ARGV[1]
local limit = ARGV[2]

local expiredMembers = redis.call("ZRANGEBYSCORE", zset_key, 0, now, "LIMIT", 0, limit)

if #expiredMembers == 0 then
	return 0
end

for _,v in ipairs(expiredMembers) do
	local ns, q, job_id = struct.unpack("Hc0Hc0Hc0", v)
	local metadata = redis.call("HMGET", table.concat({pool_prefix, ns, q, job_id}, "/"),"tries","priority") 
	if metadata !== false then
		local result = {}
		for i = 1, #metadata, 2 do
			result[metadata[i]] = metadata[i + 1]
		end
		-- only pump job to ready queue/dead letter if the job did not expire
		if result['tries'] == 0 then
			-- no more tries, move to dead letter
			local val = struct.pack("Hc0",  #job_id, job_id)
			redis.call("PERSIST", table.concat({pool_prefix, ns, q, job_id}, "/"))  -- remove ttl
			redis.call("LPUSH", table.concat({output_deadletter_prefix, ns, q}, "/"), val)
		else
			-- move to ready queue
			local val = struct.pack("Hc0", #job_id, job_id)
			redis.call("ZADD", table.concat({output_queue_prefix, ns, q}, "/"), result['priority'], val)
		end
	end
end
redis.call("ZREM", zset_key, unpack(expiredMembers))
return #expiredMembers
```

### publish 伪代码

```
hmset job metadata
if job.delay_time>0 
	timer.Add job
else
	queue.Add job
end
```

### consume 伪代码
```
if timeout > 0 
	job_id = bzpopmax(ready_queue, timeout)
else 
	job_id = zpopmax(ready_queue)
end
jobMetadata = hgetall(job_id)
if jobMetadata["tries"] <=0 
	log.error
else 
	hincrby(job.id, tries,-1)
	timer.add job
end
return jobMetadata
```

### deadletter 

可以保留使用List来实现，Respawn的时候需要修改job的metadata以及获取权重

**Comment by git-hulk** [comment]
cc @chensunny
