### ISSUE TITLE
Client golang SDK 不支持死信的删除

### ISSUE THREAD

**Issue by codcodog** [bitleak/lmstfy#74]
场景：
对死信的任务进行补偿处理，处理之后，可以删除掉死信里的任务.

使用 lmstfy client golang 的 sdk，没有发现，可以删除死信任务的方法，可以支持吗？

**Comment by git-hulk** [comment]
@liguangbo can you check and fix if missing?

**Comment by liguangbo** [comment]
https://github.com/bitleak/lmstfy/blob/master/client/client.go#L748
通过使用RespawnDeadLetter方法把死信任务重新放回就绪队列，此时死信里的任务已经被移除。通过消费就绪队列的任务，并且Ack就完成了任务的生命周期。

正常的补偿处理是不需要额外删除方法的，所以可以详细描述一下你是如何对死信任务进行补偿处理的吗？

**Comment by codcodog** [comment]
> https://github.com/bitleak/lmstfy/blob/master/client/client.go#L748
> 通过使用RespawnDeadLetter方法把死信任务重新放回就绪队列，此时死信里的任务已经被移除。通过消费就绪队列的任务，并且Ack就完成了任务的生命周期。
> 
> 正常的补偿处理是不需要额外删除方法的，所以可以详细描述一下你是如何对死信任务进行补偿处理的吗？

场景是这样的：
在进行异步任务 A，服务重启（或者其他因素）导致任务 A 进入死信了，但是我们不想重复消费，只是想拿到这个死信任务的信息，把它的数据库存储的状态置为失败就可以了，不做其他操作。

目前我是这样实现这个操作的：
```golang
// 先删除任务，再复活死信任务，防止重复消费
s.asynqClient.Ack(queue, jobID)
s.asynqClient.RespawnDeadLetter(queue, 1, 0)
```

**Comment by liguangbo** [comment]
> > https://github.com/bitleak/lmstfy/blob/master/client/client.go#L748
> > 通过使用RespawnDeadLetter方法把死信任务重新放回就绪队列，此时死信里的任务已经被移除。通过消费就绪队列的任务，并且Ack就完成了任务的生命周期。
> > 正常的补偿处理是不需要额外删除方法的，所以可以详细描述一下你是如何对死信任务进行补偿处理的吗？
> 
> 场景是这样的：
> 在进行异步任务 A，服务重启（或者其他因素）导致任务 A 进入死信了，但是我们不想重复消费，只是想拿到这个死信任务的信息，把它的数据库存储的状态置为失败就可以了，不做其他操作。
> 
> 目前我是这样实现这个操作的：
> 
> ```go
> // 先删除任务，再复活死信任务，防止重复消费
> s.asynqClient.Ack(queue, jobID)
> s.asynqClient.RespawnDeadLetter(queue, 1, 0)
> ```
这样操作是会让死信任务消失。
那是怎么拿到死信任务信息的呢？通过数据库里的jobid peekjob？

@git-hulk 实现上来说提供删除deadletter只需要```lrem deadletter pack('HHc0', 1,#job_id, job_id)``` ，这个元素是固定的一次重试。

我觉得这个场景的逻辑应该是需要重新消费，消费的时候检查任务状态，如果任务不是未执行状态为则置状态位为失败，然后Ack job？

**Comment by git-hulk** [comment]
@liguangbo 看了一下上下文，直接使用 lrem  这种 O(N) 复杂度的操作会有一些风险，如果 deadletter  比较大会直接导致大量满请求，貌似提供消费(FIFO删除) deadletter  是不是更加合理一些。

**Comment by liguangbo** [comment]
> @liguangbo 看了一下上下文，直接使用 lrem 这种 O(N) 复杂度的操作会有一些风险，如果 deadletter 比较大会直接导致大量满请求，貌似提供消费(FIFO删除) deadletter 是不是更加合理一些。

https://github.com/bitleak/lmstfy/blob/master/server/handlers/queue.go#L542
@git-hulk 现在已经有delete deadletter的接口，只是client里面还没有实现。

所以目前来看是要看 @codcodog 的具体需求，是需要消费deadletter 还是需要删除指定deadletter or 删除deadletter

**Comment by codcodog** [comment]
@liguangbo 主要是在 server 端看到有支持 delete deadletter 的接口，而 golang client 的 SDK 没有对应的方法，如果可以的话，希望可以支持下。
暂时使用 `Ack()` 再 `RespawnDeadLetter()` 来杀掉死信任务的.
问题暂时解决了，这个 issue 先关掉了，感谢。

**Comment by liguangbo** [comment]
这样，安排上。我们想多了。这个我重开一下，最近加上之后在close。感谢提供issue
