### ISSUE TITLE
token的配置放到redis中，如果token失效了，怎么办

### ISSUE THREAD

**Issue by vaxilicaihouxian** [bitleak/lmstfy#81]
假如因为一些原因，token失效了，可能就导致api访问不通了，这个是不是风险挺高的？

**Comment by git-hulk** [comment]
Lmstfy 是把 Redis 当做存储，LRU  策略应当配置为 noeviction, 不能有数据剔除

**Comment by vaxilicaihouxian** [comment]
可以支持从配置文件中读取token 刷新到 redis么？就这些管理配置都做成配置文件读取的，这样比较稳妥吧

**Comment by git-hulk** [comment]
token 是可以在线增加和减少的，本地配置方式很容易造成配置不一致的问题，这块风险并不大

**Comment by vaxilicaihouxian** [comment]
> token 是可以在线增加和减少的，本地配置方式很容易造成配置不一致的问题，这块风险并不大

token可以创建，但是假如线上的应用已经通过tokenA进行推送数据，此时tokenA在redis中没了，则全部推送都会失败了
这些配置信息是否可以提供只从配置文件读取的模式？包括pusher api配置、auth配置等这些内容

**Comment by git-hulk** [comment]
暂时可能不会考虑这么做，这种可能会导致多份配置不一致问题
