### ISSUE TITLE
请问admin的api有访问控制功能么？

### ISSUE THREAD

**Issue by vaxilicaihouxian** [bitleak/lmstfy#82]
比如简单的设置basic auth这种password方式，我看现在是都可以访问。如果只限制在本地IP的话，监控指标的获取、管理操作都不方便，但是如果直接放开外部访问的话，又比较危险

**Comment by git-hulk** [comment]
https://github.com/bitleak/lmstfy/issues/69 这个里面计划已经要加上简单的 basic auth, 目前还没加上，这周之内加上

**Comment by vaxilicaihouxian** [comment]
好的!
