### ISSUE TITLE
请问代码中的script命令可以替换成eval吗

### ISSUE THREAD

**Issue by vaxilicaihouxian** [bitleak/lmstfy#86]
我的redis服务不支持script命令 ，请问可以提供使用eval执行的代码么？

**Comment by git-hulk** [comment]
这个还没办法替换，script  命令用来计算 script SHA, 为什么你们不支持 script

**Comment by vaxilicaihouxian** [comment]
> 这个还没办法替换，script 命令用来计算 script SHA, 为什么你们不支持 script， 用了 proxy?

嗯 用了proxy，我把script的代码都注释了，直接用eval执行，应该没啥问题吧？

**Comment by git-hulk** [comment]
这个还是不建议这么做，会导致性能下降，每次执行都需要重新解析 lua script

**Comment by vaxilicaihouxian** [comment]
> 这个还是不建议这么做，会导致性能下降，每次执行都需要重新解析 lua script, 建议直连 master 或者 sentinel

嗯 这倒是，不过我们的redis是带分片的，这个是不是还不支持呢，因为我看lua脚本中的代码有多个不同的key的场景，这个没法路由到正确的slot了吧

**Comment by git-hulk** [comment]
对的，目前还不支持 sharding
