### ISSUE TITLE
单任务一直存在，需要间隔时间进行调度作业

### ISSUE THREAD

**Issue by luobobaowang1** [bitleak/lmstfy#89]
我有一个任务，他需要一直存在，每隔一段时间便进行调用一次。比如每隔五分钟更新一次缓存。我查看了api，发现并没有一个参数，可以设定为永远按间隔时间进行调用

**Comment by luobobaowang1** [comment]
我考虑过不ack ，然后设置一个很大的重试次数，但是这样总觉得很奇怪

**Comment by git-hulk** [comment]
这个可以考虑使用 republish 的功能，client 已经有了，文档漏了补充，后面补一下: https://github.com/bitleak/lmstfy/blob/master/client/client.go#L125

**Comment by luobobaowang1** [comment]
在收到你的回复之前我已经这么做了，但是我觉得这应该是一个功能优化

**Comment by luobobaowang1** [comment]
我看了https://github.com/bitleak/lmstfy/blob/master/client/client.go#L125  发现并没有ACK

我的做法是，收到作业后开始republish，然后得到一个id，如果作业失败，则delete 掉这个id，相当于手动回滚这个中间状态。如果直接ack掉作业的话，重试机制就失效了。

**Comment by liguangbo** [comment]
republish的函数有传jobid进去，作为参数，lmstfy的服务端会先ack这个job然后在创建新的
https://github.com/bitleak/lmstfy/blob/25a3811b7fb3be120942fe26648ba00ef2da2384/server/handlers/queue.go#L32

**Comment by luobobaowang1** [comment]
我明白，我的意思是，如果ack 了那么 它将不会继续重试，这样的话就破坏了重试参数。正确的做法或许应该是，先push，然后拿到这个重发的id，当出现异常的时候将这个重发的作业删除掉，使得当前任务可以在ttr 后被重新执行
