### ISSUE TITLE
[Pool.migrate]是做什么用的？什么场景下会用到另一个redis实例？求解答谢谢

### ISSUE THREAD

**Issue by zevingao** [bitleak/lmstfy#90]
[Pool.migrate]是做什么用的？什么场景下会用到另一个redis实例？求解答谢谢

**Comment by git-hulk** [comment]
比如，想迁移 Redis 实例的时候，配置 migrate 的 source/target pool, 那么在写入的时候会写到新的 pool, 消费的时候优先读老的 pool，这样老集群不再有新数据，等待消费完就可以下线。

**Comment by zevingao** [comment]
> 比如，想迁移 Redis 实例的时候，配置 migrate 的 source/target pool, 那么在写入的时候会写到新的 pool, 消费的时候优先读老的 pool，这样老集群不再有新数据，等待消费完就可以下线。

好的，明白了。还有两个问题麻烦解答一下：
1、不使用db持久化吗？ redis宕机后恢复会不会有可能丢数据？
2、这种只判断是否到期的服务，没有什么业务逻辑，部署多少个实例合适呢？

**Comment by git-hulk** [comment]
1. 使用 Redis AOF 做持久化，数据是否丢失取决于 append fsync 策略，建议使用 Redis Sentinel 在故障时做自动切换
2. LMSTFY 本身是无状态的，具体是实例数看你们自己的要求的吞吐。production 建议至少部署两个实例，避免单点问题。

**Comment by zevingao** [comment]
> 1. 使用 Redis AOF 做持久化，数据是否丢失取决于 append fsync 策略，建议使用 Redis Sentinel 在故障时做自动切换
> 2. LMSTFY 本身是无状态的，具体是实例数看你们自己的要求的吞吐。production 建议至少部署两个实例，避免单点问题。

谢谢解答。我感觉我需要加一层db持久化，查问题也容易些😀

**Comment by git-hulk** [comment]
也没什么问题

**Comment by zevingao** [comment]
> 也没什么问题

还有一个问题，消费的时候从queue pop一个job，如果没有ack，以后是不是就没可能再消费到这个job了？

**Comment by git-hulk** [comment]
consume 携带了一个 TTR(time to run), 超过这个时间会自动重试，重试次数取决于写入的 tries 参数

**Comment by zevingao** [comment]
> consume 携带了一个 TTR(time to run), 超过这个时间会自动重试，重试次数取决于写入的 tries 参数

就是说消费的时候还会去往sorted set加一个同样的job，然后到期往ready queue插入的时候是不是要判断这个job在pool中是否存在？不然就一直循环了。。。

**Comment by git-hulk** [comment]
消费的时候回检查的
